name: latex_variables
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - setuptools_scm
  - varname
  # Development requirements
  - matplotlib
  - pytest
  - pytest-cov
  - coverage
  - black>=20.8b1
  - pylint
  - flake8
  - sphinx=2.2.1
  - sphinx_rtd_theme=0.4.3
  - sphinx-gallery
  - numpydoc
